apiVersion: v1
kind: Service
metadata:
  name: spring-boot-sample
  labels:
    app: spring-boot-sample
    tire: backend
spec:
  type: NodePort
  ports:
  - port: 30000
    targetPort: 30000
    nodePort: 30000
    name: spring-boot-sample
  selector:
    app: spring-boot-sample
    tire: backend
